config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    get "about"=>"homes#about"
    resources :items, only: [:index, :show]
    get "customers/confirm_withdraw"
    patch "customers/withdraw"
    resources :customers, only: [:show, :edit, :update]
    delete "cart_items/destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm"
    get "orders/completion"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:new, :create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_one_attached :image
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum method_payment: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0, confirm: 1, production: 2, preparing: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: { cannot: 0, waiting: 1, production: 2, completion: 3}
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer.id)
  end
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
    @quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.update!(order_params)
      @order.order_details.update_all(making_status: 1) if @order.order_status == "confirm"
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  def order_params
    params.require(:order).permit(:customer_id, :address_postal_code, :address, :address_name, :postage, :money, :method_payment, :order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <h4><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
    <table>
        <tr>
            <th>会員ID</th><td><%= @customer.id %></td>
        </tr>
        <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <tr>
            <th>氏名</th><td><%= f.text_field :first_name %><%= f.text_field :last_name %></td>
        </tr>
        <tr>
            <th>フリガナ</th><td><%= f.text_field :first_name_kana %><%= f.text_field :last_name_kana %></td>
        </tr>
        <tr>
            <th>郵便番号</th><td><%= f.text_field :postal_code %></td>
        </tr>
        <tr>
            <th>住所</th><td><%= f.text_field :address %></td>
        </tr>
        <tr>
            <th>電話番号</th><td><%= f.text_field :telephone_number %></td>
        </tr>
        <tr>
            <th>メールアドレス</th><td><%= f.text_field :email %></td>
        </tr>
        <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, '有効', value: false%>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, '退会', value: true %>
            </td>
        </tr>
    </table>
    <%= f.submit '変更を保存',class:"btn btn-success" %>
        <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
    <h4>会員一覧</h4>
    <table>
        <thead>
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
        </thead>
        <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
                <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.first_name %> <%= customer.last_name %>
                <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
                <% if true == customer.is_deleted %>
                退会
                <% else %>
                有効
                <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
    </table>
    <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <h4><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h4>
    <table>
        <tr>
            <th>会員ID</th><td><%= @customer.id %></td>
        </tr>
        <tr>
            <th>氏名</th><td><%= @customer.first_name %><%= @customer.last_name %></td>
        </tr>
        <tr>
            <th>フリガナ</th><td><%= @customer.first_name_kana %><%= @customer.last_name_kana %></td>
        </tr>
        <tr>
            <th>郵便番号</th><td><%= @customer.postal_code %></td>
        </tr>
        <tr>
            <th>住所</th><td><%= @customer.address %></td>
        </tr>
        <tr>
            <th>電話番号</th><td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
            <th>メールアドレス</th><td><%= @customer.email %></td>
        </tr>
        <tr>
            <th>会員ステータス</th>
            <td>
                <% if true == @customer.is_deleted %>
                <h7>退会</h7>
                <% else %>
                <h7 class="text-success">有効</h7>
                <% end %>
            </td>
        </tr>
    </table>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
    <%= link_to "注文履歴一覧を見る", admin_root_path,class:"btn btn-primary" %>
</div>