config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    get "about"=>"homes#about"
    resources :items, only: [:index, :show]
    get "customers/confirm_withdraw"
    patch "customers/withdraw"
    resources :customers, only: [:show, :edit, :update]
    delete "cart_items/destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm"
    get "orders/completion"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:new, :create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_one_attached :image
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum method_payment: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0, confirm: 1, production: 2, preparing: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: { cannot: 0, waiting: 1, production: 2, completion: 3}
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
    @quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.update!(order_params)
      @order.order_details.update_all(making_status: 1) if @order.order_status == "confirm"
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  def order_params
    params.require(:order).permit(:customer_id, :address_postal_code, :address, :address_name, :postage, :money, :method_payment, :order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
    <h4>ジャンル編集</h4>
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
      <table>
        <tr>
          <th>ジャンル名</th>
          <td><%= f.text_field :name %></td>
          <td><%= f.submit '変更を保存',class:"btn btn-success" %></td>
        </tr>
      </table>
    <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h4>ジャンル一覧・追加</h4>
  <h5>ジャンル名</h5>
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
      <%= f.text_field :name, :placeholder=>"ジャンル名" %>
      <%= f.submit '新規登録',class:"btn btn-success" %>
    <% end %>

  <table>
    <tr>
      <th>ジャンル</th><th></th>
    </tr>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id),class:"btn btn-success" %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
<h4>注文一覧履歴</h4>
<div class="text-center">
  <table border="1" rules="rows">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to admin_order_path(order.id) do %>
            <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          <% end %>
        </td>
        <td>
            <%= order.customer.first_name %><%= order.customer.last_name %>
        </td>
        <td>
          <% quantity = 0 %>
          <% order.order_details.each do |order_detail| %>
              <% quantity += order_detail.amount %>
          <% end %>
          <%= quantity %>
        </td>
        <td>
          <%= order.order_status_i18n %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%= paginate @orders %>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
    <h4>商品編集</h4>
    <div class="row">
        <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
        <div class="row">
          <h5>商品画像</h5>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="row">
          <h5>商品名</h5>
          <%= f.text_field :name %>
        </div>
        <div class="row">
          <h5>商品説明</h5>
          <%= f.text_area :introduction %>
        </div>
        <div class="row">
          <h5>ジャンル</h5>
          <%= f.collection_select :genre_id, @genres, :id, :name %>
        </div>
        <div class="row">
          <h5>税抜価格</h5>
          <%= f.text_field :price %>円
        </div>
        <div class="row">
          <h5>販売ステータス</h5>
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, '販売中', value: true %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, '販売停止中', value: false%>
        </div>
        <div class="text-center">
          <%= f.submit '変更を保存',class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
<div class="row">
<h4>商品一覧</h4>
<h1><%= link_to "+", new_admin_item_path %></h1>
</div>
  <table class="table">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td>
          <%= item.id %>
        </td>
        <td>
          <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
          <% end %>
        </td>
        <td>
          <%= item.price.to_s(:delimited) %>
        </td>
        <td>
          <%= item.genre.name %>
        </td>
        <td>
          <% if true == item.is_active %>
          <h6 class="text-success">販売中</h6>
          <% else %>
          <h6 class="text-black-50">販売停止中</h6>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4>商品新規登録</h4>
  </div>
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row">
      <h5 >商品画像</h5>
      <%= f.file_field :image, accept: "image/*" %>
    </div>
    <div class="row">
      <h5>商品名</h5>
        <%= f.text_field :name %>
    </div>
    <div class="row">
      <h5>商品説明</h5>
        <%= f.text_area :introduction %>
    </div>
    <div class="row">
      <h5>ジャンル</h5>
        <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい" %>
        <!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->
    </div>
    <div class="row">
      <h5>税抜価格</h5>
        <%= f.text_field :price %>円
    </div>
    <div class="row">
      <h5>販売ステータス</h5>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中', value: true %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中', value: false%>
    </div>
  <div class="text-center">
      <%= f.submit '新規登録', class:"btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
    <h4>商品詳細</h4>
    <div class="row">
        <div class="col">
        <%= image_tag @item.get_image(100,100) %>
        </div>
        <div class="col">
            <table>
                <tr>
                    <th>商品名</th><td><%= @item.name %></td>
                </tr>
                <tr>
                    <th>商品説明</th><td><%= @item.introduction %></td>
                </tr>
                <tr>
                    <th>ジャンル</th><td><%= @item.genre.name %></td>
                </tr>
                <tr>
                    <th><div>税込価格</div><div>(税抜価格)</div></th><td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>円)</td>
                </tr>
                <tr>
                    <th>販売ステータス</th>
                    <td>
                        <% if true == @item.is_active %>
                        <h6 class="text-success">販売中</h6>
                        <% else %>
                        <h6 class="text-black-50">販売停止中</h6>
                        <% end %>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="text-center">
        <%= link_to "編集する", edit_admin_item_path(@item),class:"btn btn-success" %>
    </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
<h4>注文履歴詳細</h4>
<table border="0">
    <tr>
        <th>購入者</th><td><%= @order.customer.first_name %><%= @order.customer.last_name %></td>
    </tr>
    <tr>
        <th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
        <th>配送先</th><td><div>〒<%= @order.address_postal_code.to_s.insert(3, "-") %>  <%= @order.address %></div><div><%= @order.address_name %></div></td>
    </tr>
    <tr>
        <th>支払方法</th><td><%= @order.method_payment_i18n %></td>
    </tr>
    <tr>
        <th>注文ステータス</th>
        <td>
            <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses_i18n.invert , class: "order_status" %>
            <%= f.submit "更新" , class: "btn btn-success" %>
            <% end %>
        </td>
    </tr>
</table>
<div class="row">
<table border="0">
    <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製造ステータス</th>
        <th></th>
    </tr>
    <% @order.order_details.each do |order_detail| %>
    <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.money * order_detail.amount).to_s(:delimited) %></td>
        <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert , class: "making_status" %>
            <%= f.submit "更新" , class: "btn btn-success" %>
            <% end %>
        </td>
    </tr>
    <% end %>
</table>
<table border="0">
    <tr>
        <th>商品合計</th><td><%= @order.money.to_s(:delimited) %>円</td>
    </tr>
    <tr>
        <th>送料</th><td><%= @order.postage %>円</td>
    </tr>
    <tr>
        <th>請求合計額</th><td><%= (@order.money + @order.postage).to_s(:delimited) %>円</td>
    </tr>
</table>
</div>
</div>

app/views/homes/about.html.erb
<h1>about</h1>
<dev>ながのCAKEは全国発送可能なケーキ屋さんです。</div>
<div>お子様からお年寄りの方までお召し上がりいただけるように、</div>
<div>様々なバリエーションをご用意しております。</div>
<div>また全国へ発送可能ですので「いつ」でも「どこ」でも注文いただけます。</div>
<div>ぜひご注文ください。</div>