config/routes.rb
Rails.application.routes.draw do
    root to: "public/homes#top"
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  scope module: :public do
    get "about"=>"homes#about"
    resources :items, only: [:index, :show]
    get "customers/confirm_withdraw"
    patch "customers/withdraw"
    resources :customers, only: [:show, :edit, :update]
    delete "cart_items/destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post "orders/confirm"
    get "orders/completion"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  namespace :admin do
    root "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:new, :create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_one_attached :image
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details, dependent: :destroy
    enum method_payment: { credit_card: 0, transfer: 1 }
    enum order_status: { waiting: 0, confirm: 1, production: 2, preparing: 3, sent: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    enum making_status: { cannot: 0, waiting: 1, production: 2, completion: 3}
end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
    @quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @genres = Genre.all
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <a class="navbar-brand p-3" href="/">
            <span class="btn btn-light">LOGO</span>
        </a>
    <nav  class="navbar navbar-expand-lg navbar-light">
    <ul class="navbar-nav ml-auto">
    <% if admin_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "会員一覧",admin_customers_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "注文履歴一覧",admin_root_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, class:"btn btn-light", method: :delete %>
      </li>
    <% elsif customer_signed_in? %>
      <div>ようこそ、<%= current_customer.first_name %>さん！</div>
      <li>
        <%= link_to "マイページ", customer_path(current_customer.id), class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, class:"btn btn-light", method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "About", about_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light" %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path, class:"btn btn-light" %>
      </li>
    <% end %>
    </ul>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>